### ISSUE TITLE
Errors when using &lt; and &gt;

### ISSUE THREAD

**Issue by vadamovsky** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#36] opened 2014-12-31 03:46 UTC
I have added this text to an empty page:
For bold text use &lt;b&gt;this tag&lt;/b&gt;

When I switch to Source, I will get:
For bold text use &amp;lt;b&amp;gt;this tag&amp;lt;/b&amp;gt;

It seems fine. But If I switch back to the Wysiwyg editor, I will get:
For bold text use <b>this tag</b>

Which is wrong. I should receive the original:
For bold text use &lt;b&gt;this tag&lt;/b&gt;

When I add a more comlicated text to the Wysiwyg editor:
&lt;dcterms:created xsi:type="dcterms:W3CDTF"&gt;

Then after switching to the Source, back to Editor and again to the Source, I will get a <b>pareseerror</b>.

**Comment by vadamovsky** [comment] 2015-01-02 01:25
To fix the bug comment out the line 748 in <b>CKeditorParser.body.php</b>:
$finalString = $this->htmlDecode( $finalString ); //27.12.14 RL

**Comment by riparap** [comment] 2015-01-02 12:16
If that line is commented out, then another issue which is related to use of formats ie. _"italic, bold and undeline inside displayed link text"_ will come back (more details can be found here: https://www.mediawiki.org/wiki/Extension_talk:WYSIWYG#Bug_when_parsing_.3Ci.3E_inside_an_external_link_.E2.9C.94_52323). 

I was also wondering if that fix was valid or not when I made it. I could not figure out exactly how MW works, because it seems that MW is encoding html characters when it processes link text. I had to dedoce them back to make formats inside link text work properly, That fix has effect on whole page, not just link texts.

You wrote:
"It seems fine. But If I switch back to the Wysiwyg editor, I will get:
For bold text use <b>this tag</b>
Which is wrong. I should receive the original:
For bold text use &lt;b&gt;this tag&lt;/b&gt;"

<s>I disagree with this, because if you write text _`For bold text use <b>this tag</b>`_ in wikitext mode, end result will be: For bold text use <b>this tag</b>. So actually it is working like MW in that direction.</s>

This should work  properly: _`For bold text use <nowiki><b>this tag</b></nowiki>`_.

I think it is not allowed to mix html text directly with other text on page. If you have html elements which should be kept intact, then they should be isolated somehow, like with nowiki or pre tags.

**Comment by vadamovsky** [comment] 2015-01-03 01:38
Thank you for the reply. There is a small misunderstanding.
If I enter this text to the WYSIWYG editor
For bold text use &lt;b&gt;this tag&lt;/b&gt;

After switching to Source, I will get:
For bold text use &amp;lt;b&amp;gt;this tag&amp;lt;/b&amp;gt;

This is correct.
But if I swich to WYSIWYG editor I should get the original:
For bold text use &lt;b&gt;this tag&lt;/b&gt;

Instead of this I will get:
For bold text use <b>this tag</b>

Which is wrong.
Another example: Enter into an empty page in the WYSIWYG mode:
1 < 2

And now swith back to Source, to WYSIWYG and again back etc... Your result will be soon:
1&amp;lt;2 p=""&amp;gt;    

But don't worry, I have found the cause and solutions.

First, you really have to remove the bad line:
`$finalString = $this->htmlDecode( $finalString ); //27.12.14 RL`

One solution could be to call the <b>htmlDecode</b> only on substrings inside the links. But this is a bad solution.

The <b>parse</b> function from <i>includes\parser\Parser.php</i> calls the <b>internalParse</b> function.
The <b>internalParse</b> function calls the <b>replaceExternalLinks</b> function.
The <b>replaceExternalLinks</b> function calls the <b>Linker::makeExternalLink</b> function from <i>includes\Linker.php</i>.
And finally the <b>Linker::makeExternalLink</b> function calls the <b>LinkerMakeExternalLink</b> hook which is <b>makeExternalLink</b> function in <i>extensions\WYSIWYG\CKeditorLinker.php</i>.

And here you escape the link text:
`$text = htmlspecialchars( $text );`

Remove the line and the problem is solved.

Another solution is to let the MW to create the link:

```
      static function makeExternalLink( $url, $text, &$link, &$attribs, $linktype ) {
              return true;
      }
```

**Comment by riparap** [comment] 2015-01-03 12:24
Thanks for more examples, I agree that earlier fix "B551+27.12.2014" related to formats inside link texts has to be modified somehow.

Your analyze of the source of the problem is right, MW Linker::makeExternalLink is parsing the link and when rebuilding it, it will encode html characters. 

You wrote: _"..One solution could be to call the htmlDecode only on substrings inside the links. But this is a bad solution...."_. Why do you think this is bad solution? ... isn't your suggestion to comment out " $text = htmlspecialchars( $text );" in "Linker::makeExternalLink" doing just that, but only in different way ie. by "not doing" the encoding at all for links :) . ... or do you mean that there really is a bug in MW when it calls  "htmlspecialchars( $text );" in "Linker::makeExternalLink" with external links? 

I think that hacking MW files might not be so good idea, unless there really is a bug there. If there is no bug in MW then it is more like extension should adapt to behaviour of MW. I will try to test this more to see if I can fix for this. 

I have canceled "B551+27.12.2014" temporarily, because it is rather easy to have desired format with link text by just placing formats so that whole link is inside desired format, not just link text.

**Comment by vadamovsky** [comment] 2015-01-03 14:14
Why do I think that calling <b>htmlDecode</b> only on substrings inside the links is a bad idea? Because it is better not to make an error than make an error and then repair it.

We are not talking about hacking MW files.

The <b>Linker::makeExternalLink</b> is just a hook which calls <b>your</b> function <b>makeExternalLink </b> in:
<b>extensions\WYSIWYG\CKeditorLinker.php</b>

The line which escapes the tags from the link text is in <b>your</b> file <b>CKeditorLinker.php</b>:
`$text = htmlspecialchars( $text );`

Remove the line or change the <b>makeExternalLink</b> function to let the MW create the link:

```
      static function makeExternalLink( $url, $text, &$link, &$attribs, $linktype ) {
              return true;
      }
```

**Comment by riparap** [comment] 2015-01-04 19:36
I did not fully understand earlier how chain of calls were made dispite your 100% accurate explanation. I guess my brain was still fixed with my own earlier tests and also parameter "$escape = true" in Linker.php::makeExternalLink tricked me... I am not php expert, I forgot that setting means just default value. That was why I was thinking that MW was doing the encoding.

I have fixed programs as you suggested by commenting out "$text = htmlspecialchars( $text );" in WYSIWYG\CKeditorLinker.php.

This teached a lot to me about php and hooks in MW, thank you for your patience and help in fixing this.

**Comment by vadamovsky** [comment] 2015-01-04 22:40
My pleasure. :)

I'm not php expert too. I just wanted to fix the editor I want to use with the MW in our company.

Thank you for your cooperation.

If you will need in the future my help to catch an error leave me a message at:
&lt;my GitHub id&gt;@gmail.com

**Closed as completed** 2015-01-05 16:52 UTC
