### ISSUE TITLE
MediaWiki 1.26.x addOnloadHook not defined (workaroud avail. in brach wysiwyg_mw126, fixed in wysiwyg_mw126_rsl)

### ISSUE THREAD

**Issue by wzxjohn** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#82] opened 2016-02-25 09:19 UTC
In MedieWiki 1.26.2, all JavaScript file are loaded **asynchronously** by a **JavaScript loader**.
`load.php?modules=startup&only=scripts` 
It means sometimes, the `addOnloadHook()` function will be executed before the file (which defined it, `load.php?modules=jquery.accessKeyLabel,client|mediawiki.RegExp,notify,util|mediawiki.legacy.wikibits`) been completely loaded. 
So sometimes the Editor cannot be Init and only the source of the wiki page can be seen.

**Comment by riparap** [comment] 2016-02-25 11:30
It seems like  page will open in wysiwyg only one time. If page is then closed and then reopened in wysiwyg, page will open second time as html in wikieditor. When browser cache is cleared and browser restarted, then page can be again opened in wysiwyg mode once. Wysiwyg seems to work lile this in FireFox (44.0.2) and Chrome (48.0.2564.116m). With IE11, wysiwyg seems to work without problems.

Do you happen to have any ideas how this asynchronous loading could be fixed with wysiwyg so that wiki page can be opened in wysiwyg every time?

Should [this extension](https://www.mediawiki.org/wiki/Extension:Gadgets) be used?  
...please be patient with me if I ask stupid questions, this is new issue for me and I am not an expert on these fields:)

**Comment by ricordisamoa** [comment] 2016-02-25 12:15
`addOnloadHook` is deprecated, maybe use jQuery?
https://www.mediawiki.org/wiki/ResourceLoader/Legacy_JavaScript#addOnloadHook

**Comment by wzxjohn** [comment] 2016-02-26 02:38
@riparap For me, I just add 1s delay before `addOnloadHook`. This can make sure in my network environment, every JS file will be completely loaded before `addOnloadHook` been called. Maybe you can find a way to let the Wysiwyg JS file load by MediaWiki's JS loader, not by the page itself.
@ricordisamoa This actually is another problem. jQuery function also need to be called after jQuery lib been completely loaded. So just replace `addOnloadHook` with `jQuery` will not solve this problem. The real problem is how to make Wysiwyg work well with async JavaScript load.

**Comment by ricordisamoa** [comment] 2016-02-26 23:23
You can never be sure that a function has been defined after some time. Just depend on the module it is defined in (`mediawiki.legacy.wikibits`) via ResourceLoader, either statically (server side) or dynamically (client side).

**Comment by riparap** [comment] 2016-02-28 17:14
I have made some modifications in branch wysiwyg_mw126. Seems like all basic functions of wysiwyg work now with MW1.26.xx. Variable$wgFCKEditor_delay_addonloadhook of LocalSettings.php can be used to fine tune delay for running initEditor. I understand that this is not a solution and perhaps it is not even a good workaround but it seems to work also in my environment anyway. 

Next step would be to figure out how this resource loader of mediawiki works. Is there any good simple tutorial for this available somewhere?

**Comment by ricordisamoa** [comment] 2016-02-28 18:51
- [ResourceLoader/Developing with ResourceLoader](//www.mediawiki.org/wiki/ResourceLoader/Developing_with_ResourceLoader)
- [ResourceLoader/Migration guide for extension developers](//www.mediawiki.org/wiki/ResourceLoader/Migration_guide_for_extension_developers)

**Comment by riparap** [comment] 2016-03-23 13:44
I have tried to study how resorceloader works and I was able to create own module for javascripts of wysiwyg which I can also load when page is opened for editing in wysiwyg. However I was unable to attach ckeditor.js in same way. I created own module for this and if loaded it works with resourceloader in case debug mode of resource loader is used. When used in normal mode, ckeditor will not launch. I suspect problem is with local/global variables/functions (with resourceloader they are not global anymore). Any ideas how this can be fixed ? ... I already tried binding with  window.func = func style but I am not quite sure what kind of list should be created.

I was able to make it work when ckeditor.js was not loaded using resourceloader. Modified bundle using hybrid style solution (injected javascript for ckeditor.js + resourceloader for wysiwyg) is available in branch mediawiki_126_rsl).

**Comment by riparap** [comment] 2016-03-24 12:12
When trying to load javascripts of WYSIWYG and CKeditor using resourceloader, the issue with CKeditor is with location of files. It seems that I can not make resourceloader aware of location of files of CKeditor. Browser thinks that files should be directly under MW installation directory, when they in reality are in directory extensions/WYSIWYG/ckeditor. 

This happens when using normal run mode. If I use debug mode of resourceloader, wysiwyg and CKeditor starts without problems.

This kind of errors are displayed in normal run mode:
 "404 Not Found - http://xx.xx.xx.xx/mediawiki/skins/kama/editor.css?t=F969" 
 "404 Not Found - http://xx.xx.xx.xx/mediawiki/plugins/mwtemplate/images/icon_template.gif?t=F969"

Any ideas how this can be fixed?

**Comment by riparap** [comment] 2016-03-26 09:45
This is caused by resourceloader which runs CKeditor in "own" environment which for some reason can't pass installation directory information (=path of extension) to Ckeditor properly. After I added variable CKEDITOR_BASEPATH with proper path for CKeditor, it started to work without problems with resourceloader.

Branch [wysiwyg_mw126_rsl](https://github.com/Mediawiki-wysiwyg/WYSIWYG-CKeditor/tree/wysiwyg_mw126_rsl) contains latest modification for wysiwyg using MW1.26 and resourceloader (Version 1.5.6_0 [B551+26.03.2016]). 

There are still some code for style definitions which are injected into page directly without resourceloader because I could not figure out how this could be done, when they seem to be somehow user specific. I would anyway guess that wysiwyg is now 98% compatible with resourceloader :). See also #81.

**Comment by riparap** [comment] 2016-06-29 09:05
Related issue is #87.

**Comment by riparap** [comment] 2016-07-03 11:19
All javascripts are now loaded using resourceloader (except if debug mode is used, which requires two parameters to be set in LocalSettings.php).

With bundle of branch wysiwyg_mw127 (version 1.5.6_0 [B551+02.07.2016]) WYSIWYG can now be activated using wfLoadExtension- method.

**Closed as completed** 2016-07-21 11:04 UTC
