### ISSUE TITLE
Category picker not working in MW 1.24.1

### ISSUE THREAD

**Issue by DavidBeaumier** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#39] opened 2015-01-09 15:19 UTC
We installed the editor to a new MW installation 1.24.1 (only the database was upgraded from 1.17.0). The MW language is set to French. The editor version is "1.5.6_0 [B551+04.01.2015], CKEditor 4.4.5 [revision 25cdcad]". The editor works fine except for the category picker. 

Here's the behavior we have:
1. No category is loaded in the list when the picker loads
2. If we enter " " (a space) in the textbox all the categories are then loaded into the list (without indent to simulate the hierarchy of the categories)
3. When typing an existing category name we get the "no category found" message
4. If I select a category from the list, its name is tranfered to the textbox, but the message "Not found, the category is new" (in French) is shown and the listbox is emptied. However, if I click the OK button the category is added to the page.

We tested the editor with MW 1.24.1 under both Apache and IIS. We also tested with IE, Chrome and FF. We always get the same behavior.

Is this an issue other people can reproduce? Any help would be appreciated.

![image](https://cloud.githubusercontent.com/assets/3083902/5681718/dbc9cc86-97e8-11e4-9be0-f1c4616ac6eb.png)
![image](https://cloud.githubusercontent.com/assets/3083902/5681724/f2c7bd6c-97e8-11e4-8cf0-9799facf2230.png)

**Comment by riparap** [comment] 2015-01-09 17:41
About issues 1 and 2: 
It seems that for some reason version of MW has effect on how the autoupdate of selection list works.
In MW 1.22(.12) selection list is not automatically populated but f.ex in MW 1.23(.5) it is populated when dialog is opened (I tested this with both IE and FF). Based on your test it perhaps may not be autoupdated in MW1.24(.x) either.

At this moment selection list does not  support  hierarchy of the categories in any version of MW.

About issue 3 and 4:
Do you mean that when focus is in the first box and you start to type name of existing category (=name which you can see below in selection list), you will get message "Not found, category is new" under the box, and selection list becomes empty?
This is strange.... do you know how many different categories you have in your database? ...I am wondering if amount has something to do with this, In my test wiki I have only ~20 categories. 

Dialog is working for me in MW 1.22 and 1.23 (db: MySQL, character set of db: binary). At this moment I do not have possibility to test this in MW 1.24.x.

After you upgraded from 1.17 to 1.24, have you run maintenance command for new installation (something like "php ./maintenance/update.php") ? .... I gues it does not do any harm, if you run this at any time later, but i think you must have done this because I suspect that otherwise MW1.24 will not work at all if you are using database which is in old format.

When you type something in the first box, program is doing search from database using value of string you have entered. Search program is referring to "$wgContLang->checkTitleEncoding( $wgContLang->recodeInput( js_unescape( $term ) ) ). If resulting value from this is empty, nothing will be returned as search result. This is somehow related to character set encodings, At this moment I do not know exactly how. If you try to change language of your wiki session to english, does it work any better then? 

What database are you using ... is it MySQL? ... At time of installing MW, when database was built for the first time, there has been a question about character set "binary or UTF-8". Binary mode is more efficient and allows full range of unicode characters. To me it sounds little like this might be the cause of this issue or perhaps characters set mismatch of your old database compared to the new one.... this is just a lucky guess, not a fact.

One additional question unrelated to this issue:
After installing wysiwyg in MW 1.24.1, was it possible for you to edit pages using wysiwyg directly, or did you have to do modification related to issue #23 (=comment out some lines in WYSIWYG/CKeditor.body.php) ?

**Comment by Wingsofcourage** [comment] 2015-01-09 18:56
I experienced the same issue in Mediawiki 1.24 in a usual installation on mysql with english. 
May be that the interface from mediawiki has changed to get all categories or the database schema has changed. Any idea's ?

**Comment by DavidBeaumier** [comment] 2015-01-09 19:21
Based on @Wingsofcourage comment I conclude that it's not an isolated issue. One of my colleague modified some of the control JS to populate the list at the opening of the control (and he added the hierarchical support). I'll make sure we submit these change soon.

However, the search is still not working. This installation uses MySQL 5.6.17 and the server character set is UTF-8. I think we will try with a binary charset to see if it changes the behavior. I'll keep you updated.

I also noted that the category is shown as "unknown object" in the editor instead of the actual category name.
![image](https://cloud.githubusercontent.com/assets/3083902/5685675/92f60408-980a-11e4-8ef9-747b53a9f470.png)

Regarding the question about issue 3 and 4: we have 87 categories in the wiki. And yes, if we type the name of an existing category (whole or part / same case) the search fails. Same behavior if we select a category instead of typing it.

Do you have a public sandbox we can access to see what is the expected behavior for the control?

**Comment by DavidBeaumier** [comment] 2015-01-09 19:23
@Wingsofcourage which character set is defined for your installation? If you're on binary and have the issue I'm not going to try it here...

**Comment by DavidBeaumier** [comment] 2015-01-09 19:52
We tested the control on a brand new v1.24.1 installation (and an empty database) using binary charset + english locale and we had the same behavior as previously described.

**Comment by riparap** [comment] 2015-01-09 20:00
My explanation abowe about empty returned value is partly wrong. If search value changes to empty string then it means that complete list of categories should have been returned. But if it changes to something different  because of character sets, then nothing may be returned.

Ok... if you do not have imported db, then it may not be mismatch with charaters in db vs. characters entered in dialog. 

It may also be that entered search value is not for some reason passed properly into ajax search program. This sounds little strange, because it happens within dialog of CKeditor.

So far one thing that I have learned with wysiwyg is that everything is possible with it :)   ...I have to install MW 1.24 in order to test this...it may take some time though.

Text "unknown object" with category element on page is normal behaviour. It does not show name of the category in wysiwyg mode (category is visible only inside dialog).

Unfortunatedly I do not have public sandbox to demonstrate wysiwyg.

**Comment by DavidBeaumier** [comment] 2015-01-09 20:56
The workaround we now have make the control usable, although the search feature is missing. We'll let you do investigation on your side. Don't hesitate to let us know if you would like us to test a future patch.

**Comment by riparap** [comment] 2015-01-10 13:27
I can not reproduce this problem in my environment with MW1.24.1:
• Centos 6.4 
• XAMPP for Linux 1.8.3-2 (PHP to 5.5.6, MySQL to 5.6.14, Apache to 2.4.7)
• WYSIWYG  1.5.6_0 [B551+04.01.2015], CKEditor 4.4.5 [revision 25cdcad]

I took MW 1.24.1 tar bundle and did fresh installation with new mysql database (binary character set). I greated few new categories. Then I tried searh of them in dialog: list is not populated automatically, I have to key in "space" or "arrow up" in search box to get list. Search  works ok based on what I type in box. Selecting category did not give any errors. Dialog seems to work ok for me.

I tired both fixes with wysiwyg  issue #23 (modifying OutputPage.php and restoring it back and modifying CKeditor.body.php): the way #23 is fixed does not have effect on how dialog of category works.

Then I created new empty database where I imported old MW 1.23 db and run maintenance for it. Also with old categories from old db, dialog of category works ok in my environment. I used IE11 and FF 34, both works ok.

I have older MySQL version 5.6.14 than you in production but I tested this with MySQL 5.6.21 too (xampp 5.6.3-0), dialog of categories works ok there too in my test environment.

Can you somehow verify that your mysql account which is used by MW has proper user rights in db. I have used something like this: "GRANT ALL PRIVILEGES ON <db_name>.\* TO '<user>'@'localhost' IDENTIFIED BY '<password>' WITH GRANT OPTION;"

Have you tried to create new categories with wysiwyg and then search them using dialog, can they be found?

I am using skin Vector in MW, what skin are you using?

**Comment by DavidBeaumier** [comment] 2015-01-12 18:36
We are using the Vector skin too. Good news, I think we found the "issue" with the search feature: the control only search top-level categories! Our 87 categories are organized hierarchically and it's why we got the "Not found, category is new" message.

According to the MediaWiki reference on categories (http://www.mediawiki.org/wiki/Help:Categories#Managing_the_category_hierarchy): "It is a good idea to organize all categories into a hierarchy with a single top level category". However, in that case the only category the control can find is "Root". By promoting a sub-category to a top-level category it becomes "searchable".

With the previous version of the wiki (v1.17) we were using the FCKEditor. We find the categories dialog of this control to be near-perfect:
- Hierarchical display of categories
- Incremental search in all levels
- Ability to select multiple categories in a single operation
- Ability to create more than one new category in a single operation

![fckeditor](https://cloud.githubusercontent.com/assets/3083902/5708282/ab5b38e2-9a5d-11e4-8e78-9da529307fbd.png)
![categoriesdialog](https://cloud.githubusercontent.com/assets/3083902/5708287/b4be5c7a-9a5d-11e4-9a19-17e717e1f248.png)

I think the ideal solution to the current issue would be to implement a hierarchical search, but I have no idea of the required efforts. Do you think it would be easy to implement?

**Comment by riparap** [comment] 2015-01-13 09:02
Varlin has also proposed this approach earlier:
https://www.mediawiki.org/wiki/Extension_talk:WYSIWYG#Improve_categories_handling_51651. 

Is that version of FCKeditor available for download somewhere?

I guess this modification is not impossible :) ...I am not MW, php, javascript, browser nor CKeditor expert, so it is not that easy for me anyway, it would be interesting modification though. It will require at least few days work. 

Right now I am currently busy with other things so I am not able to work with this in near future. Any help or volunteers are highly appreciated.

**Comment by DavidBeaumier** [comment] 2015-01-13 13:23
The FCKEditor for MW extension is not supported anymore, but based on the archived page (http://www.mediawiki.org/w/index.php?title=Extension:FCKeditor_(Official)&oldid=676802) the extension source files are still available at http://svn.wikimedia.org/svnroot/mediawiki/trunk/extensions/FCKeditor/. 

My team is willing to work on implementing most of these features in the WYSIWYG-CKeditor in the short-term. I think we should be able to come up with a first iteration in 1-2 weeks. We'll keep you updated,

**Comment by riparap** [comment] 2015-01-19 17:51
Great work, step by step wysiwyg is going towards "near perfect" state :)

Couble of comments:

In original bundle of this version of wysiwyg, category element in wysiwyg  mode was displayed as "span.fck_mw_category" element. Advantage was that name of category was visible beside "C" element in wysiwyg mode. I have changed "C" -element to be image when I created the first dialog for categories. Do you think it would be possible to change it back to span element in wysiwyg mode?

When I reopen page in wysiwyg and double click exisiting category element  on page where there already is more than one categories defined, only name of selected category element will appear in box of selected categories. If I click button "C" in menu, list of selected categories is empty. It would be nice to always have all of existing categories of page to appear in box of selected categories.

**Comment by DavidBeaumier** [comment] 2015-01-19 18:31
Thanks. Your're right on your second comment: the "show all linked categories" feature was not part of this commit. I'm going to commit that, with some other improvements, later today or to tomorrow. 

We did not alter the editor itself. It's out-of-scope for us at this moment. We agree with you that the icon + the name of the category would be a better way of displaying categories in the editor.

My next commit will add these features to the dialog:
- Show a list of all linked categories at the opening of the dialog
- Allow the user to remove unwanted categories in the dialog + update the page categories to show only the current categories when the dialog is closed (OK)
- Always add the category icon at the end of the document (and not at the current cursor position)
- A click on any of the category icons opens a dialog where all the linked categories are displayed (related to the first item). The dialog will no longer be contextualized to a specific category.

**Comment by riparap** [comment] 2015-01-19 18:41
I agree. Your list sounds great...

**Comment by riparap** [comment] 2015-01-20 21:48
Category dialog seems to work without problems in my simple mediawiki environment. 

I made these modifications:
- added support for translations in dialog (there may be minor grammatical errors) 
- cleaned away modifications from wfSajaxSearchCategoryCKeditor, because it seems that you have restored the original code back
- removed some unnecessary elements and texts from category dialog

It is not possible to define sort option for selected category anymore so it now obeys name of page by default. To me this is not important option at all, I do not know what others might think about it.

When I have time I'll try to test if I can make it display name of category beside category element when page is edited in wysiwyg mode.

**Comment by DavidBeaumier** [comment] 2015-01-21 14:56
We are going to give a look to the latest version, but it sounds good to me.

The sort option was removed because it conflicted with multiple categories feature (the sort should be applied to which category?). For us, is perfectly acceptable to go into source mode and edit the wikitext to change the sort option when needed.

We did some experiments to add the category label next to the icon. However, we found an annoying behavior when we enabled it: the user can inadvertently alter the category name within the editor. We don't know yet if any of these options are feasible, but we would prefer them:
- Make the category label read-only
- Use a tooltip instead of a label (this would also remove the "unknown object" message)

If you can provide hints on how one of these behavior could be implemented in the CKEditor we would appreciate.

**Comment by riparap** [comment] 2015-01-21 17:10
If category definition has sort key definiton added in source view and if page and categories are later edited in wysiwyg mode I would guess that it will delete existing sort key definitions. If sort option would be re-applied in new dialog, it must be defined per selected category basis but as an free option for each selected category. I was thinking something like comma separated value after selected category, which could be added/removed when selected category is right clicked in box of selected categories ...this is just a thought i do not know if it is possible.

Unfortunatedly I do not know directly how to make label of category read-only or how to insert tooltip.

**Comment by DavidBeaumier** [comment] 2015-01-21 21:36
We are aware of the deletion of the sort key. It's unfortunate, but changing that behavior would require substantial work I believe. By the way it's the same exact behavior the FCKEditor had in version 1.17. We can live with this limitation, but would be happy if someone can fix that.

We found how to add the name of the category as a tooltip to the category icon. However, my fork is not up-to-date with the latest sources because I haven't found a way to integrate the work you didi in the category branch into my fork (I forked from v4). I'll try to integrate the changes tomorrow.

**Comment by riparap** [comment] 2015-01-22 09:23
One way to merge modifications to your clone in different branch is to download zipfile of CKeditor_V4_Category and copy modified files to your clone. There may be other more clever ways, but I am not that familar with github.

I tested tooltip too, it seems that f.ex setting "fakeElement.setAttribute('Title', category);" in category.js will create text for tooltip. It is strange, I have earlier tested this but I was unable to make it work then, I must have used wrong element earlier. In plugin.js editor.on( 'contentDom'.. with loop setting the Title in same way may perhaps fix it for existing categories of page too.

**Comment by riparap** [comment] 2015-01-22 15:18
Your way to fix tooltip is way better than what i was testing:-). All in all, great work.

In case there is spaces in names of categories, spaces will be converted to underscores. It was like this in earlier version too. Do you think it could be changed so that on selection lists dialog would display category names using spaces and convert them into underscores when dialog is closed with OK-button. Or does it cause some kind of problems with hierarchial structure of list?

**Comment by DavidBeaumier** [comment] 2015-01-22 15:56
Thanks! We're glad you like it. 

Replacing the "_" by a space should not cause any issue. We should be able to add this behavior in the next few days. My colleage @rchouine will do the job (he made the other changes too, I just commited for him).

Just to make things clear, this is the behavior we plan to implement:
- Editor: "Historic_Buildings" <=> Dialog: "Historic Buildings"
- Tootip: "Historic Buildings"

**Comment by sanketbaxi** [comment] 2015-01-23 08:13
David and riparap, thanks for the awesome work. I was trying to use your Category branch on a local deployment, but from the category pop-up, I could not select and add any categories to the selected categories list. Could you please help me with this?

Detailed description of my problem:
![add edit categories](https://cloud.githubusercontent.com/assets/10667019/5871559/91dc27c2-a305-11e4-997c-19548bc26560.PNG)
The 'Add/edit categories' pop-up box opened and displayed the available categories perfectly. However, Double clicking on any category from the 'Select category for page' box did not add it to the list of 'Selected categories for page'. Nor could I find a way to remove the currently selected category from the list.

**Comment by riparap** [comment] 2015-01-23 11:21
I have tested this with IE11 and FF35, where new dialog seems to work ok in my environment.  What is your browser version?

Does the search feature work for you in new dialog?

Is page existing page with categories... have you tried this with completely new empty page, where you try to add categories?

I do not have any hierarchy with categories in MW, I wonder if this could have something to do with your issue. On the other hand selecting / deselecting category in dialog takes place completely inside dialog so it may be possible that category data is somehow causing this problem.

**Comment by DavidBeaumier** [comment] 2015-01-23 13:31
I made some tests this morning and it works fine with IE11, Chrome 39 and 40. However I've been able to reproduce the problem with FF31 and FF35.

It's weird because it looks like the click and double-click events are not handled correctly in FF.

**Comment by sanketbaxi** [comment] 2015-01-23 13:50
I'm using FF35 myself. Weirdly, it seems to be working for riparap. 

I tried the following:
1. (FF35) Created a completely new page and tried to select categories. Still no luck. 
2. Tested in Chrome 40. Worked for new page as well as existing ones. So this is most likely an issue with the box itself. 

I do have nested categories, though. Would be difficult for me to get rid of them for testing. 

David, could you please update if you manage to get this working in FF? Thanks.

**Comment by DavidBeaumier** [comment] 2015-01-23 14:17
We found the source of the error. We are working on a fix.

I'm surprised it worked for @ripaprap on FF because we've been able to
reproduce the problem on multiple machines.

In the meantime, the workaround is to use Chrome or IE.

**Comment by rchouine** [comment] 2015-01-23 15:34
I just fixed the problem with the click and double click on categories using Firefox.
It works fine with IE, Chrome and Firefox.

**Comment by sanketbaxi** [comment] 2015-01-23 15:35
Sounds brilliant. Shame I won't be able to test it till Tuesday.

**Comment by riparap** [comment] 2015-01-23 17:00
There must have been some kind of version mismatch in my test  installation. I reinstalled version prior to your fix and it did not work in FF35. I am sorry about wrong information I gave earlier.

Your latest modification (tagged now with "1.5.6_0 [B551+23.01.2015]") seems to work with FF35 and IE11.

**Comment by riparap** [comment] 2015-01-24 18:13
I am just wondering if this was closed by my merge of branch "CKeditor_V4_Category" to branch "CKeditor_V4" because I do not recall that I pressed "close" button with this issue yet :-).

**Comment by riparap** [comment] 2015-02-01 20:41
There is problem with name of category as tooltip in case name contains double quotes. Name is displayed as tooltip properly in wysiwyg mode, but in case page is saved or source button is used, there will be parser error. 

I was unable to find a way to fix this properly, so I just removed quotes when name is stored into tooltip (category.js, plugin.js). I wonder if there is a more elegant way to fix this?

All latest modifications are currently stored in temporary test branch CKeditor_v4_HtmlComments.

**Comment by rchouine** [comment] 2015-02-02 15:08
I just tested your correction and it seems fine to me. The tooltip is only a way to identify the icons in the editor, and not having the quotes is not an issue for us. But I will keep it in mind if I think of a better solution.

**Comment by riparap** [comment] 2015-02-02 19:06
I was just wondering if there are some other characters that may cause similar behaviour. So far I have not found any other, f.ex character "&" works without problems. I agree, it is not a big issue if quotes are removed from tooltip, I can also live with that :-)

**Comment by riparap** [comment] 2015-02-05 09:46
Modifications of branch  "CKeditor_V4_Category" have been merged into branch "CKeditor_V4 ", branch "CKeditor_V4_Category" has been deleted.

**Closed as completed by riparap** 2015-02-05 09:46 UTC
