### ISSUE TITLE
Bug with $wgFCKEditorSpecialElementWithPreTag

### ISSUE THREAD

**Issue by Varlin** [Mediawiki-wysiwyg/WYSIWYG-CKeditor#59] opened 2015-03-04 14:30 UTC
I found a bug with `<pre>` tags, when `$wgFCKEditorSpecialElementWithPreTag=1;`

If I type `<pre class="blabla">lorem ipsum dolor</pre>` in source, I get `loremfckSPACEipsumfckSPACEdolor` in wysiwyg, whithout formatting.

Without the class, it displays correctly, with the grey background.

Not really a problem for me, but I noticed that.

**Comment by riparap** [comment] 2015-03-04 17:52
If you would like to edit contents of pre tag  directly on page always, you should set  `$wgFCKEditorSpecialElementWithPreTag=0;`.

Parameter `$wgFCKEditorSpecialElementWithPreTag=1;` means "display pre tags as special img-element in wysiwyg", but it does so only in case there are some attributes included with pre tag. If there are no attributes included, then it shows contents of pre -tag directly on page in wysiwyg mode in same way as when `$wgFCKEditorSpecialElementWithPreTag=0;`. 

I did it like this, because in case `$wgFCKEditorSpecialElementWithPreTag=0;`, it is not possible to edit attributes of pre tag in wysiwyg mode. So by setting  `$wgFCKEditorSpecialElementWithPreTag=1;`there would be a way to edit them in wysiwyg mode in case somebody wants to use it that way. 

Problem is with attribute name "class",  for some reason it prevents wysiwyg to display content of span tag as special img- element, instead it is displayed as text. If you use any other attribute name than "class", it works properly. Html -code created in both cases seems to be similar.

I assume this issue is related to following example where you can use class name to define display style: http://www.w3schools.com/css/tryit.asp?filename=trycss_display_none
With your example in wysiwyg there are no style `span.blahblah` available so element is displayed as plain text.

Sample with attribute name "class" (fails with img -element, works ok with pre tag on page):

```
&lt;span class="fck_mw_special" _fck_mw_customtag="true" _fck_mw_tagname="pre" _fck_mw_tagtype="t" class="blabla" _fck_mw_tagattributes="class"&gt;loremfckSPACEipsumfckSPACEdolor&lt;/span&gt; 
```

Sample with attribute name "classkoe" (works ok with img-element and pre tag on page):

```
&lt;span class="fck_mw_special" _fck_mw_customtag="true" _fck_mw_tagname="pre" _fck_mw_tagtype="t" classkoe="blabla" _fck_mw_tagattributes="classkoe"&gt;loremfckSPACEipsumfckSPACEdolor&lt;/span&gt; 
```

At this moment I do not know how to fix this.

**Comment by riparap** [comment] 2015-03-08 18:23
If you type `<pre class="blabla">lorem ipsum dolor</pre>` in source mode and switch to wysiwyg, it causes two class=".." definitions to be created inside special img-element: one for "fck_mw_special" which is used to shown image of special element and one for "blabla". I do not know for sure if this is proper html syntax. Anyway it seems that the last one, which is your manually added class is the one that wyiwyg is using for element (=unkown for wysiwyg).

When I changed it so that it will create only one definition class="fck_mw_special blah", still special img-element is not displayed. This is caused by plugin.js which currently is unable to handle this kind of definition (=it treats this as one class named "fck_mw_spcial blah", not two separate names).

If I change construct of special element so that class name fck_mw_special is the last one of the two separate class definitions, image element is displayed but manually added class value is lost when source view is toggled or page is saved. I guess this will happen with all other type of special img. elements too, in case you try to add your own classes to these elements in wikitext mode.

**Comment by riparap** [comment] 2015-03-10 09:11
This has been fixed in branch CKeditor_v4_Nowiki-Synt-Pre so that img-element of pre tag in this case is displayed properly. However, it will discard all user defined classes. 

I think using source mode like this is like trying to make wysiwyg work against its basic design concept ...it will be very chalenging operation to try to make it work 100% in all kind of imaginable situations in case editing modes and wikitext/html syntax will be mixed.

**Comment by Varlin** [comment] 2015-03-10 09:27
Ok. Personaly I have no need of preserving user defined class, so it's not
a problem for me. I use very few pre-tag (only in help page) because my
wiki is not code oriented, but I use branch CKeditor_v4_Nowiki-Synt-Pre.
And I think most people will prefer the more-wysiwyg-we-can-get solution :)

2015-03-10 10:11 GMT+01:00 riparap notifications@github.com:

**Comment by riparap** [comment] 2015-03-10 09:37
This modification has been merged into branch CKeditor_v4. Version 1.5.6_0 [B551+07.03.2015].

**Closed as completed by riparap** 2015-03-10 09:37 UTC
